server:
  port: 1210

spring:
  datasource:
    url: "jdbc:mysql://localhost"
    username: "root"
    password: "root"
  sql:
    init:
      mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true